Fix networking-calico CI (against master OpenStack)
- Mock 'network' object now needs a 'non_local_subnets' attr.

- Need to exclude Babel 2.4.0 (same as OpenStack global requirements now
  do; presumably there is something wrong with that version).

- DevStack plugin: disable the base etcd3 service

- Avoid calling db.get_security_group_rules with an empty set of
  security group IDs, as we then see this error:

  2017-06-22 09:53:14.328 16834 ERROR oslo_db.sqlalchemy.exc_filters
  [req-574e3215-ed4e-45e6-baae-7cf1f0c09a26 - -]
  DBAPIError exception wrapped from (pymysql.err.ProgrammingError)
  (1064, u"You have an error in your SQL syntax; check the manual that
  corresponds to your MySQL server version for the right syntax to use
  near '))' at line 3") [SQL: u'SELECT securitygrouprules.project_id AS
  securitygrouprules_project_id, securitygrouprules.id AS
  securitygrouprules_id, securitygrouprules.security_group_id AS
  securitygrouprules_security_group_id,
  securitygrouprules.remote_group_id AS
  securitygrouprules_remote_group_id, securitygrouprules.direction AS
  securitygrouprules_direction, securitygrouprules.ethertype AS
  securitygrouprules_ethertype, securitygrouprules.protocol AS
  securitygrouprules_protocol, securitygrouprules.port_range_min AS
  securitygrouprules_port_range_min, securitygrouprules.port_range_max
  AS securitygrouprules_port_range_max,
  securitygrouprules.remote_ip_prefix AS
  securitygrouprules_remote_ip_prefix,
  securitygrouprules.standard_attr_id AS
  securitygrouprules_standard_attr_id, standardattributes_1.id AS
  standardattributes_1_id, standardattributes_1.resource_type AS
  standardattributes_1_resource_type, standardattributes_1.description
  AS standardattributes_1_description,
  standardattributes_1.revision_number AS
  standardattributes_1_revision_number, standardattributes_1.created_at
  AS standardattributes_1_created_at, standardattributes_1.updated_at AS
  standardattributes_1_updated_at \nFROM securitygrouprules LEFT OUTER
  JOIN standardattributes AS standardattributes_1 ON
  standardattributes_1.id = securitygrouprules.standard_attr_id \nWHERE
  securitygrouprules.security_group_id IN (%(security_group_id_1)s)']
  [parameters: {u'security_group_id_1': set([])}]:
  ProgrammingError: (1064, u"You have an error in your SQL syntax; check
  the manual that corresponds to your MySQL server version for the right
  syntax to use near '))' at line 3")

- Ensure that we pass a list, not a set, as the filter for
  get_security_group_rules.

- Add CI test and gate hooks so we can see the Felix logs.

- Don't run the test_hotplug_nic test, because it's hitting a complex
  Nova/libvirt issue when trying to detach the additional interface, and
  I am fairly sure that this is not of great interest to the Calico
  mainline.

Closes-Bug: #1694499
Change-Id: Iba8095d060508b5d768e2647a77c2bcdd2d42d67