Monkey-patch eventlet before importing urllib3
As of the recent release of urllib3 1.20, the Calico DHCP agent was getting
this traceback on startup:

2017-01-25 11:36:10.286 3260 DEBUG etcd.client [-] Issuing read for key /calico/dhcp/v1/subnet with args {'waitIndex': 40, 'recursive': True, 'timeout': <urllib3.util.timeout.Timeout object at 0x7f2bf08a2f10>, 'wait': True} read /usr/local/lib/python2.7/dist-packages/etcd/client.py:547
[...]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/eventlet/hubs/poll.py", line 115, in wait
    listener.cb(fileno)
  File "/usr/local/lib/python2.7/dist-packages/eventlet/greenthread.py", line 214, in main
    result = function(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/networking_calico/agent/dhcp_agent.py", line 553, in loop
    super(SubnetWatcher, self).loop()
  File "/usr/local/lib/python2.7/dist-packages/networking_calico/logutils.py", line 21, in wrapped
    return fn(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/networking_calico/etcdutils.py", line 250, in loop
    response = self.wait_for_etcd_event()
  File "/usr/local/lib/python2.7/dist-packages/networking_calico/etcdutils.py", line 344, in wait_for_etcd_event
    timeout=self.etcd_timeout)
  File "/usr/local/lib/python2.7/dist-packages/etcd/client.py", line 562, in read
    timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/etcd/client.py", line 820, in wrapper
    params=params, timeout=timeout)
  File "/usr/local/lib/python2.7/dist-packages/etcd/client.py", line 890, in api_execute
    preload_content=False)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/request.py", line 66, in request
    **urlopen_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/request.py", line 87, in request_encode_url
    return self.urlopen(method, url, **extra_kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/poolmanager.py", line 244, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 588, in urlopen
    conn = self._get_conn(timeout=pool_timeout)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/connectionpool.py", line 241, in _get_conn
    if conn and is_connection_dropped(conn):
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/connection.py", line 27, in is_connection_dropped
    return bool(wait_for_read(sock, timeout=0.0))
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/wait.py", line 33, in wait_for_read
    return _wait_for_io_events(socks, EVENT_READ, timeout)
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/wait.py", line 22, in _wait_for_io_events
    with DefaultSelector() as selector:
  File "/usr/local/lib/python2.7/dist-packages/urllib3/util/selectors.py", line 364, in __init__
    self._epoll = select.epoll()
AttributeError: 'module' object has no attribute 'epoll'
Removing descriptor: 6
2017-01-25 11:36:10.293 3260 INFO networking_calico.etcdutils [-] Stopped: aborting load of initial dump.
2017-01-25 11:36:10.293 3260 ERROR networking_calico.etcdutils [-] Unexpected IO or etcd error, triggering resync with etcd: EtcdKeyNotFound('Key not found : /calico/v1/host',).
2017-01-25 11:36:11.295 3260 INFO networking_calico.etcdutils [-] <networking_calico.agent.dhcp_agent.CalicoEtcdWatcher object at 0x7f2bf16dd750>.loop() stopped due to self.stop == True

This was because the DHCP agent was doing eventlet monkey-patching - in
particular, removing 'epoll' from the standard select module - _after_ first
importing urllib3.  This confuses urllib3's idea of which selectors are
available in the select module.

For further discussion, see https://github.com/shazow/urllib3/issues/1104.
This commit fixes by doing eventlet monkey-patching before importing urllib3.

Change-Id: I1dc823507c28824079939cc43ac1439ef4647713